version: "3"

services:
  mongo:
    image: mongo:3.6.2-jessie
    container_name: gamification-mongo
    ports:
      - "50000:27017"
    volumes:
      - mongo-data:/data/db
  gamification-engine:
    build:
      context: .
    #image: gamification:final3
    container_name: gamification-engine
    ports:
      - "8010:8010"
      - "7777:7777"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1024m
    #     reservations:
    #       memory: 512m
    depends_on:
      - mongo
    links:
      - mongo:mongodb
    env_file: gamification.env
    volumes:
      - ./logs:/app/game-engine.web/logs
volumes:
  mongo-data:
