package it.univaq.gamification.simulation.builders.impl.fact;

import eu.trentorise.game.model.Action;
import it.univaq.gamification.simulation.builders.GameFactBuilder;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ActionFactBuilderImpl implements GameFactBuilder<ActionFactBuilderImpl, Action> {
    private String id;
    private Action action;

    @Builder
    public ActionFactBuilderImpl(String id) {
        this.id = id;
    }

    // Properly generated by lombok at build time
    @Override
    public ActionFactBuilderImpl build() {
        return null;
    }

    @Override
    public Action asOriginalPojo() {
        if (this.action == null) {
            this.action = new Action(this.id);
        }
        return this.action;
    }
}
