package it.univaq.gamification.simulation.builders.impl.fact;

import eu.trentorise.game.model.core.GameConcept;
import it.univaq.gamification.simulation.builders.GameFactBuilder;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;


@Getter
@Setter
public class GameFactBuilderImpl<P> implements GameFactBuilder<GameFactBuilderImpl<P>, GameConcept> {
    protected String id;
    protected String name;
    // TODO: Right now it's possible to specify gameConcept with the builder (that should not be possible)
    private  GameConcept gameConcept;

    @Builder(builderMethodName = "gameBuilder")
    public GameFactBuilderImpl(String id, String name) {
        this.id = id;
        this.name = name;
    }

    // Properly generated by lombok at build time
    @Override
    public GameFactBuilderImpl<P> build() {
        return null;
    }

    @Override
    public GameConcept asOriginalPojo() {
        if (this.gameConcept == null) {
            this.gameConcept = new GameConcept() {};
            this.gameConcept.setId(this.id);
            this.gameConcept.setName(this.name);
        }
        return this.gameConcept;
    }
}
