package it.univaq.gamification.simulation.builders.impl.fact;

import eu.trentorise.game.model.core.GameConcept;
import it.univaq.gamification.simulation.builders.GameFactBuilder;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;


@Getter
@Setter
@AllArgsConstructor
public class GameConceptFactBuilderImpl<P> implements GameFactBuilder<GameConceptFactBuilderImpl<P>, GameConcept> {
    protected String id;
    protected String name;

    // Properly generated by lombok at build time
    @Override
    public GameConceptFactBuilderImpl<P> build() {
        return null;
    }

    @Override
    public GameConcept asOriginalPojo() {
        return null;
    }

}
