package it.univaq.gamification.simulation.builders.impl.fact;

import eu.trentorise.game.model.Game;
import it.univaq.gamification.simulation.builders.GameFactBuilder;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class GameFactBuilderImpl implements GameFactBuilder<ActionFactBuilderImpl, Game> {
    private String id;
    private Game game;

    @Builder
    public GameFactBuilderImpl(String id) {
        this.id = id;
    }

    // Properly generated by lombok at build time
    @Override
    public ActionFactBuilderImpl build() {
        return null;
    }

    @Override
    public Game asOriginalPojo() {
        if (this.game == null) {
            this.game = new Game();
            this.game.setId(this.id);
        }
        return this.game;
    }
}
