package it.univaq.gamification.simulation.builders.impl.fact;

import eu.trentorise.game.model.InputData;
import it.univaq.gamification.simulation.builders.GameFactBuilder;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.util.Map;

@Getter
@Setter
public class InputDataFactBuilderImpl implements GameFactBuilder<InputDataFactBuilderImpl, InputData> {
    private Map<String, Object> data;
    private InputData inputData;

    @Builder
    public InputDataFactBuilderImpl(Map<String, Object> data) {
        this.data = data;
    }

    // Properly generated by lombok at build time
    @Override
    public InputDataFactBuilderImpl build() {
        return null;
    }

    @Override
    public InputData asOriginalPojo() {
        if (this.inputData == null) {
            this.inputData = new InputData(this.data);
        }
        return this.inputData;
    }
}
