package it.univaq.gamification.simulation.builders.impl.fact;

import eu.trentorise.game.model.Player;
import it.univaq.gamification.simulation.builders.GameFactBuilder;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.util.HashMap;
import java.util.Map;

@Getter
@Setter
public class PlayerFactBuilderImpl implements GameFactBuilder<PlayerFactBuilderImpl, Player> {
    private String id;
    private boolean team;
    private int totalMembers;
    private Map<String, String> levels;
    private Player player;

    @Builder
    public PlayerFactBuilderImpl(String id, boolean team, int totalMembers, Map<String, String> levels) {
        this.id = id;
        this.team = team;
        this.totalMembers = totalMembers;
        this.levels = levels;
    }

    // Properly generated by lombok at build time
    @Override
    public PlayerFactBuilderImpl build() {
        return null;
    }

    @Override
    public Player asOriginalPojo() {
        if (this.player == null) {
            this.player = new Player(this.id, this.team, this.totalMembers);
        }
        return this.player;
    }
}
