package it.univaq.gamification.simulation.builders.impl.fact;

import eu.trentorise.game.model.Propagation;
import it.univaq.gamification.simulation.builders.GameFactBuilder;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PropagationFactBuilderImpl implements GameFactBuilder<PropagationFactBuilderImpl, Propagation> {
    private String action;
    @Builder.Default
    private int level = 1;
    private Propagation propagation;

    @Builder
    public PropagationFactBuilderImpl(String action, int level) {
        this.action = action;
        this.level = level;
    }

    // Properly generated by lombok at build time
    @Override
    public PropagationFactBuilderImpl build() {
        return null;
    }

    @Override
    public Propagation asOriginalPojo() {
        if (this.propagation == null) {
            this.propagation = new Propagation(this.action, this.level);
        }
        return this.propagation;
    }
}
