package it.univaq.gamification.simulation.builders.impl.fact;


import eu.trentorise.game.model.Reward;
import it.univaq.gamification.simulation.builders.GameFactBuilder;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.util.HashMap;
import java.util.Map;

@Getter
@Setter
public class RewardFactBuilderImpl implements GameFactBuilder<RewardFactBuilderImpl, Reward> {
    private double percentage;
    private double threshold;
    @Builder.Default
    private Map<String, Double> bonusScore = new HashMap<>();
    private Reward reward;

    @Builder
    public RewardFactBuilderImpl(double percentage, double threshold, Map<String, Double> bonusScore) {
        this.percentage = percentage;
        this.threshold = threshold;
        this.bonusScore = bonusScore;
    }

    // Properly generated by lombok at build time
    @Override
    public RewardFactBuilderImpl build() {
        return null;
    }

    @Override
    public Reward asOriginalPojo() {
        if (this.reward == null) {
            this.reward = new Reward();
            this.reward.setPercentage(this.percentage);
            this.reward.setThreshold(this.threshold);
        }
        return this.reward;
    }
}
